// Embeds console/dist into the binary as a zstd-compressed static asset table.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const COMPRESS_LEVEL: i32 = 19;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("console_assets.rs");

    let console_enabled = env::var_os("CARGO_FEATURE_CONSOLE").is_some();
    let dist = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .join("console")
        .join("dist");

    println!("cargo:rerun-if-changed=console/dist");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries = String::new();

    if console_enabled {
        if dist.is_dir() {
            let mut assets = AssetBuilder {
                out_dir: &out_dir,
                next_id: 0,
            };
            assets.collect(&dist, &dist, &mut entries);
        } else {
            println!(
                "cargo:warning=console feature is on but console/dist is missing; \
                 build the UI with `npm --prefix console ci && npm --prefix console run build`"
            );
        }
    }

    let body = format!(
        "// @generated by build.rs; do not edit.\n\
         pub static ASSETS: &[(&str, &str, bool, &[u8])] = &[\n{entries}];\n"
    );
    fs::write(&dest, body).expect("write console_assets.rs");
}

struct AssetBuilder<'a> {
    out_dir: &'a Path,
    next_id: usize,
}

impl AssetBuilder<'_> {
    fn collect(&mut self, root: &Path, dir: &Path, out: &mut String) {
        let mut items: Vec<PathBuf> = fs::read_dir(dir)
            .expect("read console/dist")
            .map(|entry| entry.expect("read console asset entry").path())
            .collect();
        items.sort();

        for path in items {
            println!("cargo:rerun-if-changed={}", path.display());
            if path.is_dir() {
                self.collect(root, &path, out);
            } else {
                self.add(root, &path, out);
            }
        }
    }

    fn add(&mut self, root: &Path, path: &Path, out: &mut String) {
        let rel = path.strip_prefix(root).expect("asset under console/dist");
        let url = format!("/{}", rel.to_string_lossy().replace('\\', "/"));
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        let content_type = content_type(ext);
        let raw = fs::read(path).expect("read console asset");
        let (payload, compressed) = payload(ext, raw);
        let blob = self
            .out_dir
            .join(format!("console_asset_{}.bin", self.next_id));

        fs::write(&blob, payload).expect("write embedded console asset");
        self.next_id += 1;

        let include_path = blob.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    ({:?}, {:?}, {}, include_bytes!({:?})),\n",
            url, content_type, compressed, include_path
        ));
    }
}

// index.html stays raw (the server injects the bootstrap token at serve time);
// already-compressed binaries are left as-is.
fn payload(ext: &str, raw: Vec<u8>) -> (Vec<u8>, bool) {
    if !compressible(ext) {
        return (raw, false);
    }
    let compressed = zstd::encode_all(raw.as_slice(), COMPRESS_LEVEL).expect("zstd compress asset");
    if compressed.len() < raw.len() {
        (compressed, true)
    } else {
        (raw, false)
    }
}

fn compressible(ext: &str) -> bool {
    matches!(
        ext,
        "js" | "mjs" | "css" | "json" | "map" | "svg" | "txt" | "wasm" | "webmanifest"
    )
}

fn content_type(ext: &str) -> &'static str {
    match ext {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "gif" => "image/gif",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "ttf" => "font/ttf",
        "wasm" => "application/wasm",
        "txt" => "text/plain; charset=utf-8",
        "webmanifest" => "application/manifest+json",
        _ => "application/octet-stream",
    }
}
