blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/auralshin/neleus-db/discussions
    about: For open-ended questions and design discussion, please use Discussions.
